import esbuild from 'esbuild';
import process from 'process';
import { constants } from 'node:fs';
import { copyFile, mkdir, rm } from 'node:fs/promises';
import { builtinModules } from 'node:module';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const pluginOutDir = path.join('TestVault', '.obsidian', 'plugins', 'rchery');
const filesToDeploy = ['main.js', 'manifest.json', 'styles.css'];

async function deployFile(filename) {
	const dest = path.join(pluginOutDir, filename);
	await rm(dest, { force: true });
	await copyFile(filename, dest, constants.COPYFILE_F_REPLACE_EXISTING);
}

async function copyPluginFiles() {
	await mkdir(pluginOutDir, { recursive: true });
	await Promise.all(filesToDeploy.map((file) => deployFile(file)));
	console.log(`Deployed plugin files to ${pluginOutDir}`);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [
		{
			name: 'copy-plugin-files',
			setup(build) {
				build.onEnd(async (result) => {
					if (result.errors.length === 0) {
						await copyPluginFiles();
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
